before_build:
 - nuget restore "CustomerTestsExcel.sln" -verbosity quiet
build:
  project: CustomerTestsExcel.sln        # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
test_script:
  nunit3-console.exe tests.nunit